# Generated by Django 6.0.7 on 2026-07-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('formula', models.CharField(max_length=200)),
                ('cas_number', models.CharField(blank=True, max_length=20)),
                ('molar_mass', models.FloatField()),
                ('substance_class', models.CharField(blank=True, max_length=100)),
                ('normal_boiling_point', models.FloatField(blank=True, null=True)),
                ('critical_temperature', models.FloatField(blank=True, null=True)),
                ('critical_pressure', models.FloatField(blank=True, null=True)),
                ('acentric_factor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=200)),
                ('total_rows', models.IntegerField()),
                ('success_count', models.IntegerField()),
                ('error_count', models.IntegerField()),
                ('errors', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=200)),
                ('alias_type', models.CharField(choices=[('ru', 'Русское название'), ('en', 'English name'), ('aspen', 'Aspen Plus'), ('hysys', 'HYSYS')], max_length=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='components.component')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('conditions', models.CharField(blank=True, max_length=200)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='components.component')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.datasource')),
            ],
        ),
    ]
